#!/usr/bin/bash

temporary_file=$(mktemp)
# Temporary workaround on issue reported in #8432
# shellcheck disable=2024
sudo composer-unused --no-progress --output-format=github > "$temporary_file"
exit_code=$?

grep -v 'ignored' "$temporary_file"
exit $exit_code
