# Managed by https://github.com/linkorb/repo-ansible. Manual changes will be overwritten.
services:
  app:
    build:
      context: ../.
      dockerfile: .devcontainer/Dockerfile
      args:
        # Optional Node.js version
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/app:cached

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: mariadb
      PMA_PASSWORD: mariadb
      APACHE_PORT: 8000
    network_mode: service:db

volumes:
  mariadb-data:
