# {{ repo_managed }}
name: Security

on:
  workflow_call:

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2

    - name: Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io --username automation@linkorb.com --password-stdin

    - name: Docker pull
      run: docker pull ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
